version: '3.6'

volumes:
  db:

services: 
  app:
    image: ${REPO:-localhost}/${NAME:-wp-base}:${V:-latest}
    restart: always
    ports:
      - ${PORT:-8080}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: app
      WORDPRESS_DB_PASSWORD: app
      WORDPRESS_DB_NAME: app
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
